### PR TITLE
Remove git submodules of `algebra`, `proof-systems` and `redux-rs`

### PR DESCRIPTION
**Pull request by sebastiencs**
Patch them in `Cargo.toml` instead

### CODE REVIEW

**Comment by tizoc** [comment]
Looks good to me. The failure I see in drone is unrelated to these changes, everything seems to build fine.

**Comment by akoptelov** [comment]
@sebastiencs wouldn't it be better to make them  workspace dependencies?

**Comment by sebastiencs** [comment]
@akoptelov You're right, I will update the PR

**Comment by sebastiencs** [comment]
@akoptelov I've made them workspace dependencies locally, but that requires some changes to `mina-p2p-messages`  
 `Cargo.toml`.
Could you first merge `mina-p2p-messages`  into `openmina` ?
Or we merge this PR as-is and we make workspace dependencies later

**Comment by akoptelov** [comment]
@sebastiencs it is already merged, please rebase.

**Comment by sebastiencs** [comment]
Done, I still patch `ark-*` crates because we want to override them in all our dependencies tree, including `proof-systems`

**Pull request merged**
